/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/sandboxes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List sandboxes
         * @description Lists the organisation's sandboxes, most recently created first.
         *     Filterable by state, name, and tenant metadata.
         */
        get: operations["listSandboxes"];
        put?: never;
        /**
         * Create a sandbox
         * @description Synchronous: the call blocks until a node has acknowledged the
         *     sandbox, and returns a usable sandbox — identifier, domain, and
         *     capability token — or an error.
         *
         *     Supply `Idempotency-Key` to make retries safe: a retry with the
         *     same key returns the sandbox the first attempt created rather
         *     than creating a second one.
         */
        post: operations["createSandbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sandboxes/{sandboxId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The 24-character lowercase-alphanumeric NanoID. It is also a
                 *     hostname label component, so the alphabet excludes the hyphen,
                 *     which is the hostname label's field separator.
                 */
                sandboxId: components["parameters"]["sandboxId"];
            };
            cookie?: never;
        };
        /** Get a sandbox */
        get: operations["getSandbox"];
        put?: never;
        post?: never;
        /**
         * Delete a sandbox
         * @description Terminates the sandbox. Deleting a paused sandbox also releases
         *     its snapshot. Terminal states are retained as records: the
         *     sandbox remains readable as `terminated`.
         */
        delete: operations["deleteSandbox"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sandboxes/{sandboxId}/deadline": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The 24-character lowercase-alphanumeric NanoID. It is also a
                 *     hostname label component, so the alphabet excludes the hyphen,
                 *     which is the hostname label's field separator.
                 */
                sandboxId: components["parameters"]["sandboxId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extend a sandbox's deadline
         * @description Sets the sandbox's deadline to now plus `deadline_seconds`,
         *     bounded by the installation's maximum lease. The deadline is
         *     recorded here and enforced by the node.
         */
        post: operations["extendSandboxDeadline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sandboxes/{sandboxId}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The 24-character lowercase-alphanumeric NanoID. It is also a
                 *     hostname label component, so the alphabet excludes the hyphen,
                 *     which is the hostname label's field separator.
                 */
                sandboxId: components["parameters"]["sandboxId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause a sandbox
         * @description Snapshots the sandbox and releases its node capacity. Complete
         *     when the node reports the VM snapshotted; the snapshot's upload
         *     continues in the background, and `restorable_until` on the
         *     returned sandbox records how long the snapshot stays restorable.
         */
        post: operations["pauseSandbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sandboxes/{sandboxId}/ports": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The 24-character lowercase-alphanumeric NanoID. It is also a
                 *     hostname label component, so the alphabet excludes the hyphen,
                 *     which is the hostname label's field separator.
                 */
                sandboxId: components["parameters"]["sandboxId"];
            };
            cookie?: never;
        };
        /**
         * List port exposure records
         * @description Lists the sandbox's exposure records. A port with no record is
         *     private: reachable at its hostname with a capability token, like
         *     every other port. Records exist to make exposure explicit,
         *     durable, and auditable.
         */
        get: operations["listPorts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sandboxes/{sandboxId}/ports/{port}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Tenant application port. The configured sandbox agent port
                 *     (SDK default 50000) is reserved and cannot be exposed.
                 */
                port: number;
                /**
                 * @description The 24-character lowercase-alphanumeric NanoID. It is also a
                 *     hostname label component, so the alphabet excludes the hyphen,
                 *     which is the hostname label's field separator.
                 */
                sandboxId: components["parameters"]["sandboxId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Set a port's exposure
         * @description Records the port's exposure. `public` admits anonymous traffic
         *     to this one port — an explicit per-sandbox opt-in, recorded
         *     durably, visible in audit, and defaulting off. `private` records
         *     the port without widening access. Capability-token scope governs
         *     authenticated access and is independent of the public exposure
         *     record. Idempotent: repeating a `PUT` re-asserts the record.
         */
        put: operations["exposePort"];
        post?: never;
        /**
         * Remove a port's exposure record
         * @description Deletes the record, returning the port to the default: private,
         *     capability token required. Public traffic to the port stops.
         */
        delete: operations["unexposePort"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sandboxes/{sandboxId}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The 24-character lowercase-alphanumeric NanoID. It is also a
                 *     hostname label component, so the alphabet excludes the hyphen,
                 *     which is the hostname label's field separator.
                 */
                sandboxId: components["parameters"]["sandboxId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume a paused sandbox
         * @description Restores the snapshot onto a node. The resumed instance carries a
         *     **new epoch**: capability tokens minted against the previous
         *     instance fail closed, which is why this operation returns a fresh
         *     token alongside the sandbox.
         */
        post: operations["resumeSandbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sandboxes/{sandboxId}/token": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The 24-character lowercase-alphanumeric NanoID. It is also a
                 *     hostname label component, so the alphabet excludes the hyphen,
                 *     which is the hostname label's field separator.
                 */
                sandboxId: components["parameters"]["sandboxId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mint a capability token
         * @description Mints a capability token for the sandbox's current epoch. Every
         *     token carries the sandbox ID, the epoch, a scope, and a short
         *     expiry; there is no long-lived or unscoped credential. A scope
         *     can only narrow what the caller's own credential permits —
         *     request specific ports to mint an attenuated token suitable for
         *     a browser one-time link.
         */
        post: operations["mintSandboxToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List templates
         * @description Lists templates visible to the organisation.
         */
        get: operations["listTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/templates/{template}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A template alias or template ID. */
                template: components["schemas"]["TemplateAlias"];
            };
            cookie?: never;
        };
        /**
         * Get a template
         * @description Resolves an alias to its current record. Aliases are mutable;
         *     the artifact a sandbox is created from is resolved at admission
         *     time, so reading a template and creating from it can observe
         *     different artifacts if the alias is re-pointed in between.
         */
        get: operations["getTemplate"];
        put?: never;
        post?: never;
        /**
         * Delete a template
         * @description Retires the template record and its alias. The underlying
         *     artifact's bytes are dropped by the collector once nothing
         *     references them; existing sandboxes created from the artifact
         *     are unaffected.
         */
        delete: operations["deleteTemplate"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/templates/builds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a template build
         * @description Builds a template from an OCI image reference and a recipe. The
         *     image tag is resolved to an immutable digest when the build
         *     starts and never consulted again. The build is asynchronous:
         *     poll the build with `getTemplateBuild`, tail its output with
         *     `getTemplateBuildLogs`. On success the returned template alias,
         *     if one was requested, is pointed at the new artifact atomically.
         */
        post: operations["createTemplateBuild"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/templates/builds/{buildId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The template build identifier. */
                buildId: components["parameters"]["buildId"];
            };
            cookie?: never;
        };
        /** Get a template build */
        get: operations["getTemplateBuild"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/templates/builds/{buildId}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The template build identifier. */
                buildId: components["parameters"]["buildId"];
            };
            cookie?: never;
        };
        /**
         * Read build logs
         * @description Returns log entries starting at `offset`. Poll with the returned
         *     `next_offset` until the build reaches a terminal status; a call
         *     at the current end returns an empty page, not an error.
         */
        get: operations["getTemplateBuildLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Immutable lowercase SHA-256 content digest. */
        ArtifactId: string;
        /** @description One recipe step, executed in order inside the build VM. */
        BuildStep: {
            /** @description The command the step runs. */
            command: string;
            /** @description Environment for this step only. */
            env?: {
                [key: string]: string;
            };
        };
        CapabilityToken: {
            /**
             * Format: int64
             * @description The epoch the token was minted against.
             */
            epoch: number;
            /** Format: date-time */
            expires_at: string;
            /** @description The port scope, when narrowed. Null means the full scope. */
            ports?: number[] | null;
            /**
             * @description The bearer credential for the sandbox data plane. Carries
             *     the sandbox ID, epoch, scope, and expiry; verified by the
             *     gateway and again by the owning node. Never logged.
             */
            token: string;
        };
        CreateSandboxRequest: {
            /**
             * @description Requested lease length, from now. Bounded by the
             *     installation's maximum; omitted means the default lease.
             */
            deadline_seconds?: number;
            egress?: components["schemas"]["EgressPolicy"];
            /** @description Tenant key-value metadata, indexed for list filtering. */
            metadata?: {
                [key: string]: string;
            };
            /**
             * @description Optional name, unique within the organisation. A colliding
             *     create fails with 409 instead of quietly producing a second
             *     sandbox — idempotency for callers with a natural key.
             */
            name?: components["schemas"]["SandboxName"];
            /** @description A template alias or artifact ID. Aliases resolve at admission time. */
            template: string;
        };
        CreateTemplateBuildRequest: {
            /**
             * @description Template alias to point at the artifact when the build
             *     succeeds. Re-pointed atomically; sandboxes created from the
             *     alias mid-build keep resolving to the previous artifact.
             */
            alias?: string & components["schemas"]["TemplateAlias"];
            /**
             * @description OCI image reference. A tag is resolved to an immutable
             *     digest when the build starts and never consulted again.
             */
            image: string;
            /**
             * @description Readiness probe the warm-up waits for before capture. The
             *     captured memory image contains the environment already past
             *     this point, which is what a resume restores.
             */
            ready_command?: string;
            resources?: components["schemas"]["Resources"];
            /** @description Command started at boot, before the warm snapshot is captured. */
            start_command?: string;
            steps?: components["schemas"]["BuildStep"][];
        };
        /**
         * @description Egress allow and deny lists, fixed at create: policy is part of
         *     the sandbox's identity, not mutable state a caller can widen
         *     after the occupant is running. Entries are hostnames or CIDR
         *     blocks; deny takes precedence.
         */
        EgressPolicy: {
            allow?: string[];
            deny?: string[];
        };
        /** @description The one error shape every non-2xx response carries. */
        Error: {
            /**
             * @description Machine-readable cause, stable across releases. Examples:
             *     `invalid_request`, `unauthenticated`, `forbidden`,
             *     `not_found`, `name_taken`, `lifecycle_conflict`,
             *     `quota_exceeded`, `rate_limited`, `snapshot_expired`,
             *     `no_capacity`.
             */
            code: string;
            /** @description Human-readable detail. Never contains credentials. */
            message: string;
            /** @description The request identifier, for correlating with support and audit. */
            request_id?: string;
            /** @description Whether issuing the same request again would plausibly work. */
            retryable?: boolean;
        };
        ExposePortRequest: {
            visibility: components["schemas"]["PortVisibility"];
        };
        ExtendDeadlineRequest: {
            /** @description The new lease length, measured from now. */
            deadline_seconds: number;
        };
        /**
         * @description Enumerated cause recorded when a sandbox ends as `failed`.
         * @enum {string}
         */
        FailureReason: "node_lost" | "restore_failed" | "deadline_expired" | "drained_without_capture" | "never_acknowledged" | "snapshot_upload_abandoned" | "snapshot_expired";
        MintTokenRequest: {
            /**
             * @description Restrict the token to these ports. Omitted means the full
             *     scope the caller's credential permits; a scope can only
             *     narrow, never widen.
             */
            ports?: number[];
            /** @description Requested token lifetime, bounded by the installation's maximum. */
            ttl_seconds?: number;
        };
        /**
         * @description Canonical FissionPlane resource identifier: 24 characters from the
         *     lowercase alphanumeric NanoID alphabet (approximately 124 bits of
         *     entropy). IDs owned by external systems and content digests use their
         *     own schemas instead.
         */
        NanoId: string;
        PortExposure: {
            port: number;
            /** @description The port's public URL, `https://<port>-<sandbox_id>.<domain>`. */
            url: string;
            visibility: components["schemas"]["PortVisibility"];
        };
        PortList: {
            items: components["schemas"]["PortExposure"][];
        };
        /**
         * @description `private`: reachable at the port's hostname with a capability
         *     token whose scope permits it — the default for every port.
         *     `public`: anonymous traffic is admitted to this one tenant
         *     application port. Reserved platform ports can never be public.
         * @enum {string}
         */
        PortVisibility: "private" | "public";
        /** @description Trimmed human-readable resource description. */
        ResourceDescription: string;
        /** @description The compute shape, set by the template artifact. */
        Resources: {
            mem_mib: number;
            vcpus: number;
        };
        ResumeSandboxRequest: {
            /** @description Lease for the resumed instance, from now. Omitted means the default lease. */
            deadline_seconds?: number;
        };
        Sandbox: {
            /** Format: date-time */
            created_at: string;
            /**
             * Format: date-time
             * @description When the lease expires. Recorded here, enforced by the node.
             */
            deadline: string;
            /**
             * @description The sandbox domain suffix. A published port `p` is reachable
             *     at `https://<p>-<sandbox_id>.<domain>`.
             */
            domain: string;
            egress?: components["schemas"]["EgressPolicy"];
            /**
             * Format: int64
             * @description The instance generation. Advances on every resume and
             *     checkpoint; tokens are minted against an epoch and fail
             *     closed when it moves.
             */
            epoch: number;
            failure?: components["schemas"]["SandboxFailure"];
            /** @description Tenant key-value metadata, filterable in list. */
            metadata: {
                [key: string]: string;
            };
            /** @description Optional tenant-assigned name, unique within the organisation. */
            name?: (string & components["schemas"]["SandboxName"]) | null;
            resources: components["schemas"]["Resources"];
            /**
             * Format: date-time
             * @description Paused sandboxes only: the time past which the snapshot is no
             *     longer restorable. The platform refreshes ageing snapshots by
             *     default; this bound is what a caller sees if it cannot.
             */
            restorable_until?: string | null;
            sandbox_id: components["schemas"]["NanoId"];
            state: components["schemas"]["SandboxState"];
            /** @description The template alias the create named, if it named one. */
            template?: string | null;
            /** @description The immutable artifact the sandbox was created from, resolved at admission time. */
            template_artifact_id: string & components["schemas"]["ArtifactId"];
        };
        /** @description Present exactly when `state` is `failed`. */
        SandboxFailure: {
            /** @description Free text expanding on the reason. */
            detail?: string;
            reason: components["schemas"]["FailureReason"];
            /** @description Whether issuing the failed request again would plausibly work. */
            recoverable: boolean;
        };
        SandboxList: {
            items: components["schemas"]["Sandbox"][];
            /** @description Cursor for the next page; absent or null on the last page. */
            next_cursor?: string | null;
        };
        /** @description Tenant-assigned sandbox name, unique within an organisation. */
        SandboxName: string;
        /**
         * @description The tenant-visible states — exactly these four. Transitional
         *     states are internal: a pausing sandbox reads as `running`, a
         *     resuming one as `paused`.
         * @enum {string}
         */
        SandboxState: "running" | "paused" | "terminated" | "failed";
        /** @description A sandbox together with a capability token for its current epoch. */
        SandboxWithToken: {
            sandbox: components["schemas"]["Sandbox"];
            token: components["schemas"]["CapabilityToken"];
        };
        Template: {
            /** @description The mutable name pointing at the current artifact, if one is set. */
            alias?: (string & components["schemas"]["TemplateAlias"]) | null;
            /** @description The immutable artifact the alias currently resolves to. */
            artifact_id: string & components["schemas"]["ArtifactId"];
            /** Format: date-time */
            created_at: string;
            description?: (string & components["schemas"]["ResourceDescription"]) | null;
            resources?: components["schemas"]["Resources"];
            template_id: components["schemas"]["NanoId"];
        };
        /** @description Mutable, human-readable template alias. */
        TemplateAlias: string;
        TemplateBuild: {
            alias?: (string & components["schemas"]["TemplateAlias"]) | null;
            /** @description The produced template artifact; present once the build succeeds. */
            artifact_id?: (string & components["schemas"]["ArtifactId"]) | null;
            build_id: components["schemas"]["NanoId"];
            /** Format: date-time */
            created_at: string;
            /** @description What failed; present exactly when `status` is `failed`. */
            error?: string | null;
            /** Format: date-time */
            finished_at?: string | null;
            /** @description The image reference as requested. */
            image: string;
            /** @description The resolved immutable digest, once resolution has happened. */
            image_digest?: (string & components["schemas"]["ArtifactId"]) | null;
            status: components["schemas"]["TemplateBuildStatus"];
        };
        TemplateBuildLogEntry: {
            message: string;
            /** Format: date-time */
            timestamp: string;
        };
        TemplateBuildLogs: {
            entries: components["schemas"]["TemplateBuildLogEntry"][];
            /** @description Pass as `offset` on the next poll. */
            next_offset: number;
        };
        /**
         * @description `queued` and `building` are in progress; `succeeded` and
         *     `failed` are terminal.
         * @enum {string}
         */
        TemplateBuildStatus: "queued" | "building" | "succeeded" | "failed";
        TemplateList: {
            items: components["schemas"]["Template"][];
            next_cursor?: string | null;
        };
    };
    responses: {
        /** @description The request is malformed or fails validation. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Another lifecycle operation holds the mutex, or the sandbox's
         *     current state does not permit this operation (for example,
         *     pausing a sandbox that is already paused). Not retryable as-is;
         *     re-read the sandbox and decide.
         */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The credential is valid but does not permit this operation. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No such resource, for an authenticated caller. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description A quota or rate limit binds. `code` distinguishes which. */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Missing, malformed, or expired credential. Returned identically
         *     whether or not the addressed resource exists.
         */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description The template build identifier. */
        buildId: components["schemas"]["NanoId"];
        /** @description Opaque cursor from a previous page's `next_cursor`. */
        cursor: string;
        /** @description Page size. */
        limit: number;
        /**
         * @description The 24-character lowercase-alphanumeric NanoID. It is also a
         *     hostname label component, so the alphabet excludes the hyphen,
         *     which is the hostname label's field separator.
         */
        sandboxId: components["schemas"]["NanoId"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listSandboxes: {
        parameters: {
            query?: {
                /** @description Opaque cursor from a previous page's `next_cursor`. */
                cursor?: components["parameters"]["cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["limit"];
                /**
                 * @description Metadata filter: URL-encoded `key=value` pairs joined with
                 *     `&` (for example `run%3D42%26user%3Dalice`). A sandbox
                 *     matches when every pair matches.
                 */
                metadata?: string;
                /** @description Exact match on the tenant-assigned name. */
                name?: components["schemas"]["SandboxName"];
                state?: components["schemas"]["SandboxState"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of sandboxes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    createSandbox: {
        parameters: {
            query?: never;
            header?: {
                /** @description Idempotency key for safe retries of the create. */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSandboxRequest"];
            };
        };
        responses: {
            /** @description The sandbox is running. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxWithToken"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description The template does not exist or is not visible to this organisation. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A sandbox with the requested name already exists in this organisation. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            /** @description No node could serve the create within its deadline. Retryable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getSandbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The 24-character lowercase-alphanumeric NanoID. It is also a
                 *     hostname label component, so the alphabet excludes the hyphen,
                 *     which is the hostname label's field separator.
                 */
                sandboxId: components["parameters"]["sandboxId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The sandbox. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sandbox"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteSandbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The 24-character lowercase-alphanumeric NanoID. It is also a
                 *     hostname label component, so the alphabet excludes the hyphen,
                 *     which is the hostname label's field separator.
                 */
                sandboxId: components["parameters"]["sandboxId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The sandbox is terminated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    extendSandboxDeadline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The 24-character lowercase-alphanumeric NanoID. It is also a
                 *     hostname label component, so the alphabet excludes the hyphen,
                 *     which is the hostname label's field separator.
                 */
                sandboxId: components["parameters"]["sandboxId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtendDeadlineRequest"];
            };
        };
        responses: {
            /** @description The sandbox with its new deadline. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sandbox"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    pauseSandbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The 24-character lowercase-alphanumeric NanoID. It is also a
                 *     hostname label component, so the alphabet excludes the hyphen,
                 *     which is the hostname label's field separator.
                 */
                sandboxId: components["parameters"]["sandboxId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The sandbox is paused. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sandbox"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listPorts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The 24-character lowercase-alphanumeric NanoID. It is also a
                 *     hostname label component, so the alphabet excludes the hyphen,
                 *     which is the hostname label's field separator.
                 */
                sandboxId: components["parameters"]["sandboxId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The sandbox's exposure records. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    exposePort: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Tenant application port. The configured sandbox agent port
                 *     (SDK default 50000) is reserved and cannot be exposed.
                 */
                port: number;
                /**
                 * @description The 24-character lowercase-alphanumeric NanoID. It is also a
                 *     hostname label component, so the alphabet excludes the hyphen,
                 *     which is the hostname label's field separator.
                 */
                sandboxId: components["parameters"]["sandboxId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExposePortRequest"];
            };
        };
        responses: {
            /** @description The exposure record. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortExposure"];
                };
            };
            /**
             * @description The request is malformed, or `port` is reserved for the
             *     sandbox agent and cannot have an exposure record.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    unexposePort: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Tenant application port. The configured sandbox agent port
                 *     (SDK default 50000) is reserved and cannot be exposed.
                 */
                port: number;
                /**
                 * @description The 24-character lowercase-alphanumeric NanoID. It is also a
                 *     hostname label component, so the alphabet excludes the hyphen,
                 *     which is the hostname label's field separator.
                 */
                sandboxId: components["parameters"]["sandboxId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The record is removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    resumeSandbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The 24-character lowercase-alphanumeric NanoID. It is also a
                 *     hostname label component, so the alphabet excludes the hyphen,
                 *     which is the hostname label's field separator.
                 */
                sandboxId: components["parameters"]["sandboxId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ResumeSandboxRequest"];
            };
        };
        responses: {
            /** @description The sandbox is running again, under a new epoch. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxWithToken"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            /** @description The snapshot is no longer restorable (expired or its upload was abandoned). */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            /** @description No node could serve the resume within its deadline. Retryable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    mintSandboxToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The 24-character lowercase-alphanumeric NanoID. It is also a
                 *     hostname label component, so the alphabet excludes the hyphen,
                 *     which is the hostname label's field separator.
                 */
                sandboxId: components["parameters"]["sandboxId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MintTokenRequest"];
            };
        };
        responses: {
            /** @description A fresh capability token. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilityToken"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listTemplates: {
        parameters: {
            query?: {
                /** @description Opaque cursor from a previous page's `next_cursor`. */
                cursor?: components["parameters"]["cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of templates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A template alias or template ID. */
                template: components["schemas"]["TemplateAlias"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The template. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Template"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A template alias or template ID. */
                template: components["schemas"]["TemplateAlias"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The template is deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description The template is referenced by an in-progress build. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createTemplateBuild: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTemplateBuildRequest"];
            };
        };
        responses: {
            /** @description The build is queued. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateBuild"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getTemplateBuild: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The template build identifier. */
                buildId: components["parameters"]["buildId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The build. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateBuild"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getTemplateBuildLogs: {
        parameters: {
            query?: {
                /** @description Entry offset from which to read. */
                offset?: number;
            };
            header?: never;
            path: {
                /** @description The template build identifier. */
                buildId: components["parameters"]["buildId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of log entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateBuildLogs"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
