/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run a command to completion
         * @description Starts the command inside the sandbox and blocks until it exits
         *     or the timeout elapses. Output is captured and returned in one
         *     document, truncated at the advertised limit — for unbounded or
         *     interactive output, use the streaming surface instead.
         */
        post: operations["runCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a directory */
        get: operations["listFiles"];
        put?: never;
        post?: never;
        /** Remove a file or directory */
        delete: operations["removeFile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download a file */
        get: operations["downloadFile"];
        /** Upload a file */
        put: operations["uploadFile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/directories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a directory */
        post: operations["makeDirectory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move or rename a path */
        post: operations["moveFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/stat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read file metadata */
        get: operations["statFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/processes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List processes
         * @description Lists the processes the agent supervises inside the sandbox.
         */
        get: operations["listProcesses"];
        put?: never;
        /**
         * Start a background process
         * @description Starts a supervised process and returns as soon as it has been
         *     spawned. Attach to its WebSocket stream for live output, stdin,
         *     signals, and PTY resize.
         */
        post: operations["startProcess"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/processes/{pid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: number;
            };
            cookie?: never;
        };
        /** Get a process */
        get: operations["getProcess"];
        put?: never;
        post?: never;
        /**
         * Signal a process
         * @description Sends `signal` to the process. The default is SIGTERM.
         */
        delete: operations["killProcess"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/processes/{pid}/logs": {
        parameters: {
            query?: {
                /** @description Return output after this sequence number. */
                after?: number;
            };
            header?: never;
            path: {
                pid: number;
            };
            cookie?: never;
        };
        /**
         * Read buffered process output
         * @description Returns output currently retained in the process ring. Use the
         *     WebSocket stream to follow new output.
         */
        get: operations["getProcessLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CommandResult: {
            /** @description The command's exit code; negative means killed by a signal. */
            exit_code: number;
            stderr: string;
            stdout: string;
            /**
             * @description True when output exceeded the capture limit. The streaming
             *     surface has no such limit.
             */
            truncated?: boolean;
        };
        /** @description The same error shape the control plane uses. */
        Error: {
            code: string;
            message: string;
            request_id?: string;
            retryable?: boolean;
        };
        FileInfo: {
            kind: components["schemas"]["FileKind"];
            mode: string;
            /** Format: date-time */
            modified_at: string;
            name: string;
            path: string;
            size: number;
            /** @description Symlink target; absent for other kinds. */
            target?: string;
        };
        /** @enum {string} */
        FileKind: "file" | "directory" | "symlink" | "other";
        FileList: {
            items: components["schemas"]["FileInfo"][];
        };
        MakeDirectoryRequest: {
            mode?: string;
            /** @default true */
            parents: boolean;
            path: string;
        };
        MoveFileRequest: {
            destination: string;
            /** @default false */
            overwrite: boolean;
            source: string;
        };
        Process: {
            command: string;
            exit_code?: number | null;
            /** Format: date-time */
            exited_at?: string | null;
            pid: number;
            pty: boolean;
            running: boolean;
            /** Format: date-time */
            started_at: string;
        };
        ProcessList: {
            items: components["schemas"]["Process"][];
        };
        ProcessLogChunk: {
            data: string;
            sequence: number;
            /** @enum {string} */
            stream: "stdout" | "stderr";
        };
        ProcessLogs: {
            chunks: components["schemas"]["ProcessLogChunk"][];
            exit_code?: number | null;
            next_sequence: number;
            running: boolean;
            truncated_before?: number;
        };
        PtySize: {
            cols: number;
            rows: number;
        };
        RunCommandRequest: {
            args?: string[];
            /** @description The program to run. */
            command: string;
            /** @description Working directory. Omitted means the default user's home. */
            cwd?: string;
            /** @description Environment variables set for this command only. */
            env?: {
                [key: string]: string;
            };
            /** @description Bytes written to the command's stdin before it is closed. */
            stdin?: string;
            /**
             * @description Kill the command if it has not exited after this long.
             *     Omitted means the agent's default.
             */
            timeout_seconds?: number;
        };
        StartProcessRequest: {
            args?: string[];
            command: string;
            cwd?: string;
            env?: {
                [key: string]: string;
            };
            pty?: components["schemas"]["PtySize"];
        };
    };
    responses: {
        /** @description The request is malformed or fails validation. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The requested mutation conflicts with an existing path. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The requested process or path does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The per-sandbox concurrent-connection cap is reached. */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Missing, expired, or out-of-scope token, or a token minted
         *     against a previous epoch.
         */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Absolute path or a path relative to the default user's home. */
        path: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    runCommand: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCommandRequest"];
            };
        };
        responses: {
            /** @description The command ran; `exit_code` reports how it ended. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description The command did not exit within `timeout_seconds`; it has been killed. */
            408: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The per-sandbox concurrent-connection cap is reached. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listFiles: {
        parameters: {
            query: {
                /** @description Absolute path or a path relative to the default user's home. */
                path: components["parameters"]["path"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The directory entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    removeFile: {
        parameters: {
            query: {
                /** @description Absolute path or a path relative to the default user's home. */
                path: components["parameters"]["path"];
                recursive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The path was removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    downloadFile: {
        parameters: {
            query: {
                /** @description Absolute path or a path relative to the default user's home. */
                path: components["parameters"]["path"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The file bytes. */
            200: {
                headers: {
                    "X-File-Mode"?: string;
                    "X-File-Modified-At"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    uploadFile: {
        parameters: {
            query: {
                /** @description Unix permission bits in octal, for example `0644`. */
                mode?: string;
                /** @description Absolute path or a path relative to the default user's home. */
                path: components["parameters"]["path"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description The file was written atomically. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    makeDirectory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MakeDirectoryRequest"];
            };
        };
        responses: {
            /** @description The directory exists. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    moveFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveFileRequest"];
            };
        };
        responses: {
            /** @description The path was moved. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    statFile: {
        parameters: {
            query: {
                /** @description Absolute path or a path relative to the default user's home. */
                path: components["parameters"]["path"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metadata for the path. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileInfo"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listProcesses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The supervised processes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    startProcess: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartProcessRequest"];
            };
        };
        responses: {
            /** @description The process was started. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Process"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getProcess: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Process"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    killProcess: {
        parameters: {
            query?: {
                signal?: "SIGTERM" | "SIGKILL" | "SIGINT" | "SIGHUP";
            };
            header?: never;
            path: {
                pid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signal is delivered. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getProcessLogs: {
        parameters: {
            query?: {
                /** @description Return output after this sequence number. */
                after?: number;
            };
            header?: never;
            path: {
                pid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Buffered output and process status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessLogs"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
